/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author DELL
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        menu_background = new javax.swing.JPanel();
        home_icon = new javax.swing.JLabel();
        menulist = new javax.swing.JLabel();
        ToLogOut = new javax.swing.JButton();
        ToBorrowTicketMenu = new javax.swing.JButton();
        ToUserMenu = new javax.swing.JButton();
        ToBookMenu = new javax.swing.JButton();
        content_menubackground = new javax.swing.JPanel();
        design_by = new javax.swing.JPanel();
        group_6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sachmoicapnhat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_background.setBackground(new java.awt.Color(102, 0, 0));

        home_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menulist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menulist.setForeground(new java.awt.Color(242, 242, 242));
        menulist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menulist.setText("MENU LIST");

        ToLogOut.setBackground(new java.awt.Color(102, 0, 0));
        ToLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ToLogOut.setText("LOG OUT");
        ToLogOut.setBorderPainted(false);
        ToLogOut.setContentAreaFilled(false);
        ToLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToLogOutActionPerformed(evt);
            }
        });

        ToBorrowTicketMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToBorrowTicketMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToBorrowTicketMenu.setText("BORROW");
        ToBorrowTicketMenu.setBorder(null);
        ToBorrowTicketMenu.setContentAreaFilled(false);

        ToUserMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToUserMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToUserMenu.setText("USERS");
        ToUserMenu.setBorder(null);
        ToUserMenu.setContentAreaFilled(false);
        ToUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUserMenuActionPerformed(evt);
            }
        });

        ToBookMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToBookMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToBookMenu.setText("BOOKS");
        ToBookMenu.setBorder(null);
        ToBookMenu.setContentAreaFilled(false);

        javax.swing.GroupLayout menu_backgroundLayout = new javax.swing.GroupLayout(menu_background);
        menu_background.setLayout(menu_backgroundLayout);
        menu_backgroundLayout.setHorizontalGroup(
            menu_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menulist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ToLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(ToBorrowTicketMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ToUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ToBookMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu_backgroundLayout.setVerticalGroup(
            menu_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_backgroundLayout.createSequentialGroup()
                .addComponent(home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menulist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ToBookMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToBorrowTicketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(ToLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menu_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 390));

        design_by.setBackground(new java.awt.Color(204, 0, 102));

        group_6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        group_6.setForeground(new java.awt.Color(242, 242, 242));
        group_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        group_6.setText("A BOOK A DAY KEEPS THE TEACHER AWAY");

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("_____");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("_____");

        javax.swing.GroupLayout design_byLayout = new javax.swing.GroupLayout(design_by);
        design_by.setLayout(design_byLayout);
        design_byLayout.setHorizontalGroup(
            design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, design_byLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        design_byLayout.setVerticalGroup(
            design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(design_byLayout.createSequentialGroup()
                .addGroup(design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(design_byLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(group_6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addGroup(design_byLayout.createSequentialGroup()
                        .addGroup(design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(design_byLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3))
                            .addGroup(design_byLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout sachmoicapnhatLayout = new javax.swing.GroupLayout(sachmoicapnhat);
        sachmoicapnhat.setLayout(sachmoicapnhatLayout);
        sachmoicapnhatLayout.setHorizontalGroup(
            sachmoicapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        sachmoicapnhatLayout.setVerticalGroup(
            sachmoicapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("LASTEST UPDATES");

        javax.swing.GroupLayout content_menubackgroundLayout = new javax.swing.GroupLayout(content_menubackground);
        content_menubackground.setLayout(content_menubackgroundLayout);
        content_menubackgroundLayout.setHorizontalGroup(
            content_menubackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sachmoicapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addComponent(design_by, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        content_menubackgroundLayout.setVerticalGroup(
            content_menubackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(design_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(sachmoicapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(content_menubackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUserMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUserMenuActionPerformed

    private void ToLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToLogOutActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_ToLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToBookMenu;
    private javax.swing.JButton ToBorrowTicketMenu;
    private javax.swing.JButton ToLogOut;
    private javax.swing.JButton ToUserMenu;
    private javax.swing.JPanel content_menubackground;
    private javax.swing.JPanel design_by;
    private javax.swing.JLabel group_6;
    private javax.swing.JLabel home_icon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel menu_background;
    private javax.swing.JLabel menulist;
    private javax.swing.JPanel sachmoicapnhat;
    // End of variables declaration//GEN-END:variables
}
