/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code_and_db.Admin;
import code_and_db.Books;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookPopUpMenu = new javax.swing.JPopupMenu();
        AddBook = new javax.swing.JMenuItem();
        RemoveBook = new javax.swing.JMenuItem();
        FindBook = new javax.swing.JMenuItem();
        UpdateBook = new javax.swing.JMenuItem();
        UserPopUpMenu = new javax.swing.JPopupMenu();
        AddUser = new javax.swing.JMenuItem();
        RemoveUser = new javax.swing.JMenuItem();
        FindUser = new javax.swing.JMenuItem();
        UpdateUser = new javax.swing.JMenuItem();
        BorrowPopUpMenu = new javax.swing.JPopupMenu();
        AddBorrow = new javax.swing.JMenuItem();
        RemoveBorrow = new javax.swing.JMenuItem();
        menu_background = new javax.swing.JPanel();
        home_icon = new javax.swing.JLabel();
        ToLogOut = new javax.swing.JButton();
        ToBorrowTicketMenu = new javax.swing.JButton();
        ToUserMenu = new javax.swing.JButton();
        ToBookMenu = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        content_menubackground = new javax.swing.JPanel();
        design_by = new javax.swing.JPanel();
        group_6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MenuMainScreen = new javax.swing.JTabbedPane();
        LatestUpdates = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddBooks = new javax.swing.JPanel();
        Bookname_Field = new javax.swing.JTextField();
        Book_Name = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Publisher = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        Publisher_Field = new javax.swing.JTextField();
        Category_Field = new javax.swing.JTextField();
        Author_Field = new javax.swing.JTextField();
        AddBookbutton = new javax.swing.JButton();
        Volume = new javax.swing.JLabel();
        Volume_Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Quantity_Field = new javax.swing.JTextField();
        ID_Field = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        RemoveBooks = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ID_BOOK = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RemoveBookbutton = new javax.swing.JButton();
        FindBooks = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        FindIDBooks = new javax.swing.JLabel();
        FindIDBook_Field = new javax.swing.JTextField();
        FindCategory = new javax.swing.JLabel();
        FindCategory_Field = new javax.swing.JTextField();
        FindBookName = new javax.swing.JLabel();
        FindName_Field = new javax.swing.JTextField();
        FindAuthor = new javax.swing.JLabel();
        FindAuthor_Field = new javax.swing.JTextField();
        FindBookbutton = new javax.swing.JButton();
        FindTablepanel = new javax.swing.JPanel();
        FindScrollpane = new javax.swing.JScrollPane();
        FindTable = new javax.swing.JTable();
        AddUsers = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Gender_Field = new javax.swing.JTextField();
        Contact_number = new javax.swing.JLabel();
        Contactnumber_Field = new javax.swing.JTextField();
        AddUserbutton = new javax.swing.JButton();
        Address_Field = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        CCCD = new javax.swing.JLabel();
        CCCD_Field = new javax.swing.JTextField();
        FindUsers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        FindUserCCCD = new javax.swing.JLabel();
        FindUserCCCD_Field = new javax.swing.JTextField();
        FindGender = new javax.swing.JLabel();
        FindGender_Field = new javax.swing.JTextField();
        FindUserName = new javax.swing.JLabel();
        FindUserName_Field = new javax.swing.JTextField();
        FindUserbutton = new javax.swing.JButton();
        FindUserTablepane = new javax.swing.JPanel();
        FindUserScrollPane = new javax.swing.JScrollPane();
        FindUserTable = new javax.swing.JTable();
        UpdateUsers = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        UpdateBooks = new javax.swing.JPanel();
        AddBorrows = new javax.swing.JPanel();
        RemoveBorrows = new javax.swing.JPanel();
        RemoveUsers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ID_User = new javax.swing.JLabel();
        UserRemove_Field = new javax.swing.JTextField();
        RemoveUserbutton = new javax.swing.JButton();

        BookPopUpMenu.setBackground(new java.awt.Color(102, 0, 0));
        BookPopUpMenu.setForeground(new java.awt.Color(242, 242, 242));
        BookPopUpMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddBook.setBackground(new java.awt.Color(102, 0, 0));
        AddBook.setText("Add a book");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });
        BookPopUpMenu.add(AddBook);

        RemoveBook.setText("Remove a book");
        RemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBookActionPerformed(evt);
            }
        });
        BookPopUpMenu.add(RemoveBook);

        FindBook.setText("Find a book");
        FindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBookActionPerformed(evt);
            }
        });
        BookPopUpMenu.add(FindBook);

        UpdateBook.setText("Update a book's info");
        UpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookActionPerformed(evt);
            }
        });
        BookPopUpMenu.add(UpdateBook);

        AddUser.setText("Add an user");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        UserPopUpMenu.add(AddUser);

        RemoveUser.setText("Remove an user");
        RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserActionPerformed(evt);
            }
        });
        UserPopUpMenu.add(RemoveUser);

        FindUser.setText("Find an user");
        FindUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindUserActionPerformed(evt);
            }
        });
        UserPopUpMenu.add(FindUser);

        UpdateUser.setText("Update an user's info");
        UpdateUser.setToolTipText("");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });
        UserPopUpMenu.add(UpdateUser);

        AddBorrow.setText("Add a borrow ticket");
        AddBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBorrowActionPerformed(evt);
            }
        });
        BorrowPopUpMenu.add(AddBorrow);

        RemoveBorrow.setText("Remove a borrow ticket");
        RemoveBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBorrowActionPerformed(evt);
            }
        });
        BorrowPopUpMenu.add(RemoveBorrow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_background.setBackground(new java.awt.Color(102, 0, 0));

        home_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ToLogOut.setBackground(new java.awt.Color(102, 0, 0));
        ToLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ToLogOut.setText("LOG OUT");
        ToLogOut.setBorderPainted(false);
        ToLogOut.setContentAreaFilled(false);
        ToLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToLogOutActionPerformed(evt);
            }
        });

        ToBorrowTicketMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToBorrowTicketMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToBorrowTicketMenu.setText("BORROW");
        ToBorrowTicketMenu.setBorder(null);
        ToBorrowTicketMenu.setContentAreaFilled(false);
        ToBorrowTicketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBorrowTicketMenuActionPerformed(evt);
            }
        });

        ToUserMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToUserMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToUserMenu.setText("USERS");
        ToUserMenu.setBorder(null);
        ToUserMenu.setContentAreaFilled(false);
        ToUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUserMenuActionPerformed(evt);
            }
        });

        ToBookMenu.setBackground(new java.awt.Color(102, 0, 0));
        ToBookMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToBookMenu.setText("BOOKS");
        ToBookMenu.setBorder(null);
        ToBookMenu.setContentAreaFilled(false);
        ToBookMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBookMenuActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(102, 0, 0));
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu-icon.png"))); // NOI18N
        HomeButton.setBorder(null);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_backgroundLayout = new javax.swing.GroupLayout(menu_background);
        menu_background.setLayout(menu_backgroundLayout);
        menu_backgroundLayout.setHorizontalGroup(
            menu_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_backgroundLayout.createSequentialGroup()
                .addComponent(home_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton)
                .addGap(38, 38, 38))
            .addComponent(ToLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(ToBorrowTicketMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ToUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ToBookMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu_backgroundLayout.setVerticalGroup(
            menu_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_backgroundLayout.createSequentialGroup()
                .addGroup(menu_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menu_backgroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(HomeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(ToBookMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ToUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ToBorrowTicketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(ToLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menu_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 390));

        design_by.setBackground(new java.awt.Color(204, 0, 102));

        group_6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        group_6.setForeground(new java.awt.Color(242, 242, 242));
        group_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        group_6.setText("A BOOK A DAY KEEPS THE TEACHER AWAY");

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("_____");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("_____");

        javax.swing.GroupLayout design_byLayout = new javax.swing.GroupLayout(design_by);
        design_by.setLayout(design_byLayout);
        design_byLayout.setHorizontalGroup(
            design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, design_byLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        design_byLayout.setVerticalGroup(
            design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(design_byLayout.createSequentialGroup()
                .addGroup(design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(design_byLayout.createSequentialGroup()
                        .addGroup(design_byLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(design_byLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3))
                            .addGroup(design_byLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(design_byLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(group_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MenuMainScreen.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LATEST UPDATES");

        javax.swing.GroupLayout LatestUpdatesLayout = new javax.swing.GroupLayout(LatestUpdates);
        LatestUpdates.setLayout(LatestUpdatesLayout);
        LatestUpdatesLayout.setHorizontalGroup(
            LatestUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LatestUpdatesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        LatestUpdatesLayout.setVerticalGroup(
            LatestUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LatestUpdatesLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 326, Short.MAX_VALUE))
        );

        MenuMainScreen.addTab("main", LatestUpdates);

        Bookname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bookname_FieldActionPerformed(evt);
            }
        });

        Book_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Book_Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Book_Name.setText("Name");

        Category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Category.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Category.setText("Category");

        Publisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Publisher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Publisher.setText("Publisher");

        Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Author.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Author.setText("Author");

        Publisher_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Publisher_FieldActionPerformed(evt);
            }
        });

        Category_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_FieldActionPerformed(evt);
            }
        });

        Author_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Author_FieldActionPerformed(evt);
            }
        });

        AddBookbutton.setBackground(new java.awt.Color(102, 0, 0));
        AddBookbutton.setForeground(new java.awt.Color(242, 242, 242));
        AddBookbutton.setText("ADD");
        AddBookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookbuttonActionPerformed(evt);
            }
        });

        Volume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Volume.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Volume.setText("Volume");

        Volume_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volume_FieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD BOOK");

        Quantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Quantity.setText("Quantity");

        Quantity_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantity_FieldActionPerformed(evt);
            }
        });

        ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_FieldActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ID.setText("ID");

        javax.swing.GroupLayout AddBooksLayout = new javax.swing.GroupLayout(AddBooks);
        AddBooks.setLayout(AddBooksLayout);
        AddBooksLayout.setHorizontalGroup(
            AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBooksLayout.createSequentialGroup()
                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBooksLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddBooksLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBooksLayout.createSequentialGroup()
                                .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Author_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBooksLayout.createSequentialGroup()
                                .addComponent(Publisher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Publisher_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBooksLayout.createSequentialGroup()
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBooksLayout.createSequentialGroup()
                                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quantity_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddBooksLayout.createSequentialGroup()
                                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Book_Name)
                                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bookname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Category_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddBooksLayout.createSequentialGroup()
                                .addComponent(Volume, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddBookbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Volume_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        AddBooksLayout.setVerticalGroup(
            AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBooksLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID)
                    .addComponent(Bookname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book_Name))
                .addGap(18, 18, 18)
                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publisher_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Publisher)
                    .addComponent(Category)
                    .addComponent(Category_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Author)
                    .addComponent(Author_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volume)
                    .addComponent(Volume_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity)
                    .addComponent(AddBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        MenuMainScreen.addTab("add books", AddBooks);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("REMOVE BOOK");

        ID_BOOK.setText("ID");

        RemoveBookbutton.setBackground(new java.awt.Color(102, 0, 0));
        RemoveBookbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveBookbutton.setForeground(new java.awt.Color(242, 242, 242));
        RemoveBookbutton.setText("Remove");
        RemoveBookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBookbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemoveBooksLayout = new javax.swing.GroupLayout(RemoveBooks);
        RemoveBooks.setLayout(RemoveBooksLayout);
        RemoveBooksLayout.setHorizontalGroup(
            RemoveBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemoveBooksLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(ID_BOOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(RemoveBookbutton)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        RemoveBooksLayout.setVerticalGroup(
            RemoveBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveBooksLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(RemoveBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_BOOK)
                    .addComponent(RemoveBookbutton))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        MenuMainScreen.addTab("remove books", RemoveBooks);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("FIND BOOKS");

        FindIDBooks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindIDBooks.setText("ID");

        FindCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindCategory.setText("Category");

        FindBookName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindBookName.setText("Name");

        FindAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindAuthor.setText("Author");

        FindAuthor_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindAuthor_FieldActionPerformed(evt);
            }
        });

        FindBookbutton.setBackground(new java.awt.Color(102, 0, 0));
        FindBookbutton.setForeground(new java.awt.Color(242, 242, 242));
        FindBookbutton.setText("Find");
        FindBookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBookbuttonActionPerformed(evt);
            }
        });

        FindTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Publisher", "Author", "Volume", "Quantity"
            }
        ));
        FindTable.setShowVerticalLines(true);
        FindScrollpane.setViewportView(FindTable);

        javax.swing.GroupLayout FindTablepanelLayout = new javax.swing.GroupLayout(FindTablepanel);
        FindTablepanel.setLayout(FindTablepanelLayout);
        FindTablepanelLayout.setHorizontalGroup(
            FindTablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FindScrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        FindTablepanelLayout.setVerticalGroup(
            FindTablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FindScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout FindBooksLayout = new javax.swing.GroupLayout(FindBooks);
        FindBooks.setLayout(FindBooksLayout);
        FindBooksLayout.setHorizontalGroup(
            FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindBooksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindCategory)
                    .addComponent(FindIDBooks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindCategory_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindIDBook_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FindBooksLayout.createSequentialGroup()
                        .addComponent(FindBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(FindBooksLayout.createSequentialGroup()
                        .addComponent(FindAuthor)
                        .addGap(7, 7, 7)))
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(FindAuthor_Field)
                    .addComponent(FindName_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(206, 206, 206))
            .addGroup(FindBooksLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(FindBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FindBooksLayout.createSequentialGroup()
                .addComponent(FindTablepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FindBooksLayout.setVerticalGroup(
            FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindIDBooks)
                    .addComponent(FindBookName)
                    .addComponent(FindName_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindIDBook_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FindBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindCategory)
                    .addComponent(FindCategory_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindAuthor)
                    .addComponent(FindAuthor_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FindBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FindTablepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        MenuMainScreen.addTab("find books", FindBooks);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ADD USER");

        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Username.setText("Name");

        Gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gender.setText("Gender");

        Gender_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gender_FieldActionPerformed(evt);
            }
        });

        Contact_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contact_number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Contact_number.setText("Contact Number");

        Contactnumber_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contactnumber_FieldActionPerformed(evt);
            }
        });

        AddUserbutton.setBackground(new java.awt.Color(102, 0, 0));
        AddUserbutton.setForeground(new java.awt.Color(242, 242, 242));
        AddUserbutton.setText("ADD");
        AddUserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserbuttonActionPerformed(evt);
            }
        });

        Address_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_FieldActionPerformed(evt);
            }
        });

        Address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Address.setText("Address");

        CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CCCD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CCCD.setText("CCCD");

        CCCD_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCCD_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddUsersLayout = new javax.swing.GroupLayout(AddUsers);
        AddUsers.setLayout(AddUsersLayout);
        AddUsersLayout.setHorizontalGroup(
            AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUsersLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addComponent(Gender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUsersLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(213, 213, 213))
            .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddUsersLayout.createSequentialGroup()
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddUsersLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(Gender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUsersLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Contact_number)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Contactnumber_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(34, 34, 34)
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CCCD))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CCCD_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddUserbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        AddUsersLayout.setVerticalGroup(
            AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUsersLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(Username)
                .addGap(44, 44, 44)
                .addComponent(Gender)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddUsersLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CCCD)
                        .addComponent(CCCD_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Address)
                        .addComponent(Gender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(AddUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Contact_number)
                        .addComponent(Contactnumber_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddUserbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        MenuMainScreen.addTab("add users", AddUsers);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("FIND USERS");

        FindUserCCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindUserCCCD.setText("CCCD");

        FindGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindGender.setText("Gender");

        FindUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindUserName.setText("Name");

        FindUserbutton.setBackground(new java.awt.Color(102, 0, 0));
        FindUserbutton.setForeground(new java.awt.Color(242, 242, 242));
        FindUserbutton.setText("Find");

        FindUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CCCD", "Name", "Gender", "Address", "Contact Number"
            }
        ));
        FindUserTable.setShowVerticalLines(true);
        FindUserScrollPane.setViewportView(FindUserTable);

        javax.swing.GroupLayout FindUserTablepaneLayout = new javax.swing.GroupLayout(FindUserTablepane);
        FindUserTablepane.setLayout(FindUserTablepaneLayout);
        FindUserTablepaneLayout.setHorizontalGroup(
            FindUserTablepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FindUserScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        FindUserTablepaneLayout.setVerticalGroup(
            FindUserTablepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindUserTablepaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FindUserScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout FindUsersLayout = new javax.swing.GroupLayout(FindUsers);
        FindUsers.setLayout(FindUsersLayout);
        FindUsersLayout.setHorizontalGroup(
            FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindUsersLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FindUsersLayout.createSequentialGroup()
                        .addComponent(FindUserCCCD)
                        .addGap(21, 21, 21)
                        .addComponent(FindUserCCCD_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(FindUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FindUsersLayout.createSequentialGroup()
                        .addComponent(FindGender)
                        .addGap(12, 12, 12)
                        .addComponent(FindGender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindUserbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindUserName_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, Short.MAX_VALUE))
            .addComponent(FindUserTablepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(207, 207, 207))
        );
        FindUsersLayout.setVerticalGroup(
            FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindUsersLayout.createSequentialGroup()
                .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FindUsersLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FindUserCCCD_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FindUsersLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FindUserCCCD)
                                    .addComponent(FindUserName)))))
                    .addGroup(FindUsersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FindUserName_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(10, 10, 10)
                .addGroup(FindUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FindUsersLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(FindGender))
                    .addComponent(FindGender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindUserbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FindUserTablepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuMainScreen.addTab("find users", FindUsers);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("UPDATE USERS");

        javax.swing.GroupLayout UpdateUsersLayout = new javax.swing.GroupLayout(UpdateUsers);
        UpdateUsers.setLayout(UpdateUsersLayout);
        UpdateUsersLayout.setHorizontalGroup(
            UpdateUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUsersLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel11)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        UpdateUsersLayout.setVerticalGroup(
            UpdateUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUsersLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        MenuMainScreen.addTab("update users", UpdateUsers);

        javax.swing.GroupLayout UpdateBooksLayout = new javax.swing.GroupLayout(UpdateBooks);
        UpdateBooks.setLayout(UpdateBooksLayout);
        UpdateBooksLayout.setHorizontalGroup(
            UpdateBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        UpdateBooksLayout.setVerticalGroup(
            UpdateBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        MenuMainScreen.addTab("update books", UpdateBooks);

        javax.swing.GroupLayout AddBorrowsLayout = new javax.swing.GroupLayout(AddBorrows);
        AddBorrows.setLayout(AddBorrowsLayout);
        AddBorrowsLayout.setHorizontalGroup(
            AddBorrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        AddBorrowsLayout.setVerticalGroup(
            AddBorrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        MenuMainScreen.addTab("add borrow", AddBorrows);

        javax.swing.GroupLayout RemoveBorrowsLayout = new javax.swing.GroupLayout(RemoveBorrows);
        RemoveBorrows.setLayout(RemoveBorrowsLayout);
        RemoveBorrowsLayout.setHorizontalGroup(
            RemoveBorrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        RemoveBorrowsLayout.setVerticalGroup(
            RemoveBorrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        MenuMainScreen.addTab("remove borrw", RemoveBorrows);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("REMOVE USER");

        ID_User.setText("ID");

        RemoveUserbutton.setBackground(new java.awt.Color(102, 0, 0));
        RemoveUserbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveUserbutton.setForeground(new java.awt.Color(242, 242, 242));
        RemoveUserbutton.setText("Remove");
        RemoveUserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemoveUsersLayout = new javax.swing.GroupLayout(RemoveUsers);
        RemoveUsers.setLayout(RemoveUsersLayout);
        RemoveUsersLayout.setHorizontalGroup(
            RemoveUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveUsersLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(ID_User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserRemove_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(RemoveUserbutton)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemoveUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(188, 188, 188))
        );
        RemoveUsersLayout.setVerticalGroup(
            RemoveUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveUsersLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(RemoveUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserRemove_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_User)
                    .addComponent(RemoveUserbutton))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        MenuMainScreen.addTab("remove users", RemoveUsers);

        javax.swing.GroupLayout content_menubackgroundLayout = new javax.swing.GroupLayout(content_menubackground);
        content_menubackground.setLayout(content_menubackgroundLayout);
        content_menubackgroundLayout.setHorizontalGroup(
            content_menubackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addComponent(design_by, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addComponent(MenuMainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        content_menubackgroundLayout.setVerticalGroup(
            content_menubackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_menubackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(design_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuMainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(content_menubackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Side bar
    private void ToUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUserMenuActionPerformed
        UserPopUpMenu.show(ToUserMenu, WIDTH + 139, WIDTH);
    }//GEN-LAST:event_ToUserMenuActionPerformed

    private void ToLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToLogOutActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_ToLogOutActionPerformed

    private void ToBookMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBookMenuActionPerformed
        BookPopUpMenu.show(ToBookMenu, WIDTH + 139, WIDTH);
    }//GEN-LAST:event_ToBookMenuActionPerformed

    private void ToBorrowTicketMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBorrowTicketMenuActionPerformed
        BorrowPopUpMenu.show(ToBorrowTicketMenu, WIDTH + 139, WIDTH);
    }//GEN-LAST:event_ToBorrowTicketMenuActionPerformed

    
    // pop up menu options action    
    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        MenuMainScreen.setSelectedComponent(AddBooks);
    }//GEN-LAST:event_AddBookActionPerformed

    private void RemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBookActionPerformed
        MenuMainScreen.setSelectedComponent(RemoveBooks);
    }//GEN-LAST:event_RemoveBookActionPerformed

    private void FindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBookActionPerformed
        MenuMainScreen.setSelectedComponent(FindBooks);
    }//GEN-LAST:event_FindBookActionPerformed

    private void UpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookActionPerformed
        MenuMainScreen.setSelectedComponent(UpdateBooks);
    }//GEN-LAST:event_UpdateBookActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        MenuMainScreen.setSelectedComponent(AddUsers);
    }//GEN-LAST:event_AddUserActionPerformed

    private void RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserActionPerformed
        MenuMainScreen.setSelectedComponent(RemoveUsers);
    }//GEN-LAST:event_RemoveUserActionPerformed

    private void FindUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindUserActionPerformed
        MenuMainScreen.setSelectedComponent(FindUsers);
    }//GEN-LAST:event_FindUserActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        MenuMainScreen.setSelectedComponent(UpdateUsers);
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void AddBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBorrowActionPerformed
        MenuMainScreen.setSelectedComponent(AddBorrows);
    }//GEN-LAST:event_AddBorrowActionPerformed

    private void RemoveBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBorrowActionPerformed
        MenuMainScreen.setSelectedComponent(RemoveBorrows);
    }//GEN-LAST:event_RemoveBorrowActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        MenuMainScreen.setSelectedComponent(LatestUpdates);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Gender_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gender_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gender_FieldActionPerformed

    private void Contactnumber_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contactnumber_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contactnumber_FieldActionPerformed

    private void AddUserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserbuttonActionPerformed

    private void Address_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address_FieldActionPerformed

    private void CCCD_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCCD_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCCD_FieldActionPerformed

    private void RemoveBookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBookbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveBookbuttonActionPerformed

    private void RemoveUserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveUserbuttonActionPerformed

    private void Quantity_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantity_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantity_FieldActionPerformed

    private void Volume_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volume_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Volume_FieldActionPerformed

    private void AddBookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookbuttonActionPerformed
        try {
            if (ID_Field.getText().isEmpty() || Bookname_Field.getText().isEmpty() || Category_Field.getText().isEmpty() || Publisher_Field.getText().isEmpty() || Author_Field.getText().isEmpty() || Volume_Field.getText().isEmpty() || Quantity_Field.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All fields must be filled in", "Error", JOptionPane.ERROR_MESSAGE);
                ID_Field.requestFocus();
            }else{
                String id = ID_Field.getText();
                String name = Bookname_Field.getText();
                String category = Category_Field.getText();
                String publisher = Publisher_Field.getText();
                String author = Author_Field.getText();
                String volume = Volume_Field.getText();
                int quantity = Integer.parseInt(Quantity_Field.getText());
                Books newBook = new Books(id,name, category, publisher, author, volume, quantity);
                Admin.ADDBOOKS(newBook);
                ID_Field.setText("");
                Bookname_Field.setText(""); 
                Category_Field.setText(""); 
                Publisher_Field.setText(""); 
                Author_Field.setText(""); 
                Volume_Field.setText(""); 
                Quantity_Field.setText("");
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_AddBookbuttonActionPerformed

    private void Author_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Author_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Author_FieldActionPerformed

    private void Category_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_FieldActionPerformed

    private void Publisher_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Publisher_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Publisher_FieldActionPerformed

    private void Bookname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookname_FieldActionPerformed

    private void ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_FieldActionPerformed

    private void FindAuthor_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindAuthor_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindAuthor_FieldActionPerformed

    private void FindBookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBookbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindBookbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddBook;
    private javax.swing.JButton AddBookbutton;
    private javax.swing.JPanel AddBooks;
    private javax.swing.JMenuItem AddBorrow;
    private javax.swing.JPanel AddBorrows;
    private javax.swing.JMenuItem AddUser;
    private javax.swing.JButton AddUserbutton;
    private javax.swing.JPanel AddUsers;
    private javax.swing.JLabel Address;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JLabel Author;
    private javax.swing.JTextField Author_Field;
    private javax.swing.JPopupMenu BookPopUpMenu;
    private javax.swing.JLabel Book_Name;
    private javax.swing.JTextField Bookname_Field;
    private javax.swing.JPopupMenu BorrowPopUpMenu;
    private javax.swing.JLabel CCCD;
    private javax.swing.JTextField CCCD_Field;
    private javax.swing.JLabel Category;
    private javax.swing.JTextField Category_Field;
    private javax.swing.JLabel Contact_number;
    private javax.swing.JTextField Contactnumber_Field;
    private javax.swing.JLabel FindAuthor;
    private javax.swing.JTextField FindAuthor_Field;
    private javax.swing.JMenuItem FindBook;
    private javax.swing.JLabel FindBookName;
    private javax.swing.JButton FindBookbutton;
    private javax.swing.JPanel FindBooks;
    private javax.swing.JLabel FindCategory;
    private javax.swing.JTextField FindCategory_Field;
    private javax.swing.JLabel FindGender;
    private javax.swing.JTextField FindGender_Field;
    private javax.swing.JTextField FindIDBook_Field;
    private javax.swing.JLabel FindIDBooks;
    private javax.swing.JTextField FindName_Field;
    private javax.swing.JScrollPane FindScrollpane;
    private javax.swing.JTable FindTable;
    private javax.swing.JPanel FindTablepanel;
    private javax.swing.JMenuItem FindUser;
    private javax.swing.JLabel FindUserCCCD;
    private javax.swing.JTextField FindUserCCCD_Field;
    private javax.swing.JLabel FindUserName;
    private javax.swing.JTextField FindUserName_Field;
    private javax.swing.JScrollPane FindUserScrollPane;
    private javax.swing.JTable FindUserTable;
    private javax.swing.JPanel FindUserTablepane;
    private javax.swing.JButton FindUserbutton;
    private javax.swing.JPanel FindUsers;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField Gender_Field;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID_BOOK;
    private javax.swing.JTextField ID_Field;
    private javax.swing.JLabel ID_User;
    private javax.swing.JPanel LatestUpdates;
    private javax.swing.JTabbedPane MenuMainScreen;
    private javax.swing.JLabel Publisher;
    private javax.swing.JTextField Publisher_Field;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField Quantity_Field;
    private javax.swing.JMenuItem RemoveBook;
    private javax.swing.JButton RemoveBookbutton;
    private javax.swing.JPanel RemoveBooks;
    private javax.swing.JMenuItem RemoveBorrow;
    private javax.swing.JPanel RemoveBorrows;
    private javax.swing.JMenuItem RemoveUser;
    private javax.swing.JButton RemoveUserbutton;
    private javax.swing.JPanel RemoveUsers;
    private javax.swing.JButton ToBookMenu;
    private javax.swing.JButton ToBorrowTicketMenu;
    private javax.swing.JButton ToLogOut;
    private javax.swing.JButton ToUserMenu;
    private javax.swing.JMenuItem UpdateBook;
    private javax.swing.JPanel UpdateBooks;
    private javax.swing.JMenuItem UpdateUser;
    private javax.swing.JPanel UpdateUsers;
    private javax.swing.JPopupMenu UserPopUpMenu;
    private javax.swing.JTextField UserRemove_Field;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel Volume;
    private javax.swing.JTextField Volume_Field;
    private javax.swing.JPanel content_menubackground;
    private javax.swing.JPanel design_by;
    private javax.swing.JLabel group_6;
    private javax.swing.JLabel home_icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menu_background;
    // End of variables declaration//GEN-END:variables
}
